### ISSUE TITLE
Encrypt issue

### ISSUE THREAD

**Issue by wkethman** [SamMousa/limesurvey-encrypt#2]
Limesurvey Version 2.05+ Build 140717

Unfortunately, unzipped Encrypt.zip into plugin directory, enabled the plugin, turned on encryption for responses under Survey --> Global Settings after placing public key in the plugin settings generated by the following commands:

openssl genrsa -out mykey.pem 1024
openssl rsa -in mykey.pem -pubout > mykey.pub

After several responses were entered, the number of encrypted responses remains 0 - please let me know if you know any fixes available or if I can help solve the problem.

**Comment by wkethman** [comment]
Just as a thought - was searching for limitations to the encrypt script - http://php.net/manual/en/function.openssl-public-encrypt.php

And instead of using 1024 I used 2048 bit (as shown below)

openssl genrsa -out mykey.pem 2048
openssl rsa -in mykey.pem -pubout > mykey.pub

Could you provide the mechanism by which you generate the keys along with exactly what you enter into the LimeSurvey key setting - want to make sure everything is correct on that end

**Comment by SamMousa** [comment]
Hi William,

When this plugin was originally created the parameter type of the key was set to "HTML". At that time Limesurvey rendered an HTML value as a normal textarea field.
Currently Limesurvey renders a more advanced editor for HTML fields.
The problem is that the openssl key gets malformed when HTML tags are added.

I have fixed this issue in the latest version of the plugin and latest version of Limesurvey 2.05.
Please wait for a new Limesurvey version to be released and reenter the key after upgrading.

If you want to test it now you could try to switch the HTML editor to source mode and enter they key there.

Hope this helps,

**Comment by wkethman** [comment]
I am using Limesurvey 2.05 as well as your most updated Plugin

I have also just dumped the Key into the Encrypt.php file - so that it is is independent of any HTML settings. 

How do you generate your public key? Maybe it is not liking the 2048 bit code.

**Comment by wkethman** [comment]
I am trying to trouble shoot the issue because encryption is important for our application, here is a list of tests that I have completed

Failed - Tested lower bit encryption key - 512
Failed - Tested this key both in the HTML field and as hardcoded in the Encrypt.php file
Failed - Turned off the inline editing
Failed - Wrote a key generator script to ensure that keys were being generated correctly

Failed as defined by Number of encrypted responses remaining 0 after entering another survey

Would be happy to discuss the issues online - I am happy to debug more or work to communicate my issues better if needed. I really appreciate your help and thank you for your time.

**Comment by SamMousa** [comment]
Skype sam_mousa

**Comment by wkethman** [comment]
Sent contact request
